### ISSUE TITLE
Bot broke at Line 184 in data.txt

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/ConstAssemblyBot#1]
The bot broke at this line:

```     "Where there is no vision the people perish." (Applause).```

`last_line.txt` had:
```
184
5
```

**Comment by atulprakash1** [comment]
text = text.replace('."', '".')  # step 1. bot.py line 61
line_char = lines[line_to_tweet].find(first_sentence) + len(first_sentence) # step 2 bot.py line 118

find(first_sentence) in step 2 fails the match for statements having ." (dot and a quote) as the text is now converted in step 1 to ". (quote and a dot)

This causes the bot to rotate on the same line.

**Comment by rhnvrm** [comment]
This has become more apparent now that the speakers have started to have longer speeches. When the bot breaks, manual intervention is required to fix it. I'm not sure, if standardization is the way to go, but I'll leave this issue open for a while to figure out another solution.

As a temporary fix,
I currently roll back the bot to the correct point, delete erroneous tweets and run `sed -i '2157s/\.\"/\"\./' data.txt` when the bot fails at a specific line.

**Comment by rhnvrm** [comment]
I'm thinking to replace the sentence splitter with this package https://github.com/berkmancenter/mediacloud-sentence-splitter

It is based on scripts written for [EuroParl corpus](http://www.statmt.org/europarl/)

**Comment by KhaleelKhan** [comment]
Is there a specific reason `sentence_splitter` was implemented? Why not just put out the entire paragraph as a tweet (and its replies). Doing so will keep tweets in context and avoid short tweets that don't fill out the char limit.

**Comment by rhnvrm** [comment]
Hey

This was an editorial decision by @kumbhakaran to stick to short tweets after our trial runs before launching. We tried a few formats and this one seemed to be the most unique. Some of the gems we got out of this short tweet format were very RT'able as well. My personal opinion on this, I think this is a good way to make a boring medium more accessible to a new audience and a new creative experiment as well. My understanding here is that, the goal here is to not be a place where people can read these, but get introduced to and be aware about the past. Twitter is definitely not the place where you should be studying these tweets. This is a similar take on how it would be weird to start reading/analyzing from https://twitter.com/IAM_SHAKESPEARE instead of the actual books. 

I'm sure we can discuss formats, maybe @kumbhakaran would like to chip in.

**Comment by KhaleelKhan** [comment]
Hey,

Thank you for the detailed reply.

> This was an editorial decision by @kumbhakaran to stick to short tweets after our trial runs before launching. We tried a few formats and this one seemed to be the most unique. Some of the gems we got out of this short tweet format were very RT'able as well.

That's fair enough, given the limitations of the platform, i guess this format fits the best. How about adding speaker name to tweets, I think tweets will carry more 'weight' this way. This is just a suggestion and its ultimately the your / @kumbhakaran 's decision.

As for Parsing the data, how about separating the parse logic and the tweeting bot?
The parser can run once every time `data.txt` changes and transform / save data in a python friendly format (eg. pandas). If it somehow fails we can fix the parse logic instead of waiting for bot to fail.

**Comment by rhnvrm** [comment]
Closed via https://github.com/rhnvrm/ConstAssemblyBot/commit/e91ba7e822af0737e6d0a529d2f85b46aa5ee918

Regarding the other suggestions, can you please create another issue, we can continue the discussion there.
