### ISSUE TITLE
Bot failed at line 2157

### ISSUE THREAD

**Issue by rhnvrm** [rhnvrm/ConstAssemblyBot#13]
The bot broke at line 2157 after tweeting 
```
"Until yesterday, Dr. Jayakar, I was entirely in favour of your Resolut
ion but Mr. Jinnah's Press Conference in London as made the whole difference
". I said, "What difference has it made?"
```

**Comment by KhaleelKhan** [comment]
Did the bot crash? I wasn't able to reproduce any issue by setting
`line_to_tweet = 2156, line_char = 3650`

**Comment by rhnvrm** [comment]
This issue needs more investigation. I am able to guess at that moment that the issue was related to what was saved to last_line.txt after running `bot.py`. Most likely it would be related to our sentence parsing logic #1

**Comment by rhnvrm** [comment]
Closed via https://github.com/rhnvrm/ConstAssemblyBot/commit/e91ba7e822af0737e6d0a529d2f85b46aa5ee918
