### ISSUE TITLE
Bot broke at line 2514

### ISSUE THREAD

**Issue by KhaleelKhan** [rhnvrm/ConstAssemblyBot#15]
Middle tweet is out of place :

![const_bug](https://user-images.githubusercontent.com/23614468/85124314-fd391000-b229-11ea-93fd-9537ca512bb9.png)

Line for reference:
> I would like just to say a few words with regard to another aspect of the question. The Resolution i**s there, but, how are we going to implement it?** What are the impediments that we already see before us which may prevent us from carrying this Resolution into effect? Now, one, of course, is the status of the Constituent Assembly in the absence of the Muslim League. Dr. Jayakar yesterday referred to some analogy of a dinner party. **He said, "If guests are invited and some guests do not come, then how can you have the dinner party?"** But he forgot to say what will be the fate of the guests who have already arrived? 

Looks like bot rolled back to an earlier point in the same line, it continues from there. Possibly an error writing to last_line.txt ?

**Comment by rhnvrm** [comment]
This seems to be related to #13 and something to do with our sentence parsing logic and quotes. 

I'll work on https://github.com/rhnvrm/ConstAssemblyBot/issues/1#issuecomment-643801592 over the weekend and see if switching to a proper parser will fix these issues.

**Comment by rhnvrm** [comment]
Closed via https://github.com/rhnvrm/ConstAssemblyBot/commit/e91ba7e822af0737e6d0a529d2f85b46aa5ee918
