### ISSUE TITLE
Bot split tweet mid-word

### ISSUE THREAD

**Issue by KhaleelKhan** [rhnvrm/ConstAssemblyBot#7]
Bot split the word here:

>> I know that. That is exactly the point for which I have praised Dr. Rajendra Prasad and hope he will extend to us the same consideration for placing our point of view as you would to any others, because it has always been our experience that when it com

>> es to a question of our placing our views we are invariably asked to be brief.

Char count of first sentence: 253

**Comment by rhnvrm** [comment]
Thanks for reporting, merging with #3 for easier tracking.
